spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XE
    username: app_user
    password: app123
    driver-class-name: oracle.jdbc.OracleDriver

  sql:
    init:
      mode: never

server:
  port: 8080
